print("welcome to the band name generator")
city = input("Which city did u grew up in?\n")
pet = input("What is the name of your pet?\n")
print(pet)
print(city)
print("Your band name could be " + city + " " + pet)