famous_people_data = {
    "Lionel Messi": {"name": "Lionel Messi", "follower": 460, "profession": "Footballer", "country": "Argentina"},
    "Taylor Swift": {"name": "Taylor Swift", "follower": 275, "profession": "Singer-Songwriter", "country": "United States"},
    "Dwayne 'The Rock' Johnson": {"name": "Dwayne 'The Rock' Johnson", "follower": 395, "profession": "Actor, Professional Wrestler", "country": "United States"},
    "Virat Kohli": {"name": "Virat Kohli", "follower": 265, "profession": "Cricketer", "country": "India"},
    "Ariana Grande": {"name": "Ariana Grande", "follower": 380, "profession": "Singer, Actress", "country": "United States"},
    "Kim Kardashian": {"name": "Kim Kardashian", "follower": 355, "profession": "Media Personality, Businesswoman", "country": "United States"},
    "Selena Gomez": {"name": "Selena Gomez", "follower": 420, "profession": "Singer, Actress, Producer", "country": "United States"},
    "LeBron James": {"name": "LeBron James", "follower": 160, "profession": "Basketball Player", "country": "United States"},
    "Neymar Jr.": {"name": "Neymar Jr.", "follower": 215, "profession": "Footballer", "country": "Brazil"},
    "Billie Eilish": {"name": "Billie Eilish", "follower": 110, "profession": "Singer-Songwriter", "country": "United States"},
    "Shakira": {"name": "Shakira", "follower": 90, "profession": "Singer, Songwriter, Dancer", "country": "Colombia"},
    "Cristiano Ronaldo": {"name": "Cristiano Ronaldo", "follower": 600, "profession": "Footballer", "country": "Portugal"},
    "Kylie Jenner": {"name": "Kylie Jenner", "follower": 400, "profession": "Media Personality, Businesswoman", "country": "United States"},
    "Justin Bieber": {"name": "Justin Bieber", "follower": 290, "profession": "Singer-Songwriter", "country": "Canada"},
    "Elon Musk": {"name": "Elon Musk", "follower": 170, "profession": "Entrepreneur, CEO of SpaceX and Tesla", "country": "United States"},
    "Beyoncé": {"name": "Beyoncé", "follower": 325, "profession": "Singer, Actress, Businesswoman", "country": "United States"},
    "Drake": {"name": "Drake", "follower": 140, "profession": "Rapper, Singer, Actor", "country": "Canada"},
    "Jennifer Lopez": {"name": "Jennifer Lopez", "follower": 250, "profession": "Singer, Actress, Dancer", "country": "United States"},
    "David Beckham": {"name": "David Beckham", "follower": 80, "profession": "Former Footballer, Businessman", "country": "United Kingdom"},
    "Will Smith": {"name": "Will Smith", "follower": 75, "profession": "Actor, Producer, Rapper", "country": "United States"},
    "Zendaya": {"name": "Zendaya", "follower": 160, "profession": "Actress, Singer", "country": "United States"},
    "Gal Gadot": {"name": "Gal Gadot", "follower": 110, "profession": "Actress, Model", "country": "Israel"}
}
